FROM alpine:latest as certificates
RUN apk update && apk add --no-cache ca-certificates && update-ca-certificates



FROM scratch
COPY --from=certificates /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY cyber_power /app/cyber_power

EXPOSE 8080
WORKDIR /app
ENTRYPOINT [ "/app/cyber_power" ]
